DROP TABLE IF EXISTS "public"."users";
-- This script only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.

-- Sequence
CREATE SEQUENCE IF NOT EXISTS users_user_id_seq;

-- Table Definition
CREATE TABLE "public"."users" (
    "user_id" int4 NOT NULL DEFAULT nextval('users_user_id_seq'::regclass),
    "username" varchar NOT NULL,
    "email" varchar NOT NULL,
    PRIMARY KEY ("user_id")
);

INSERT INTO "public"."users" ("user_id", "username", "email") VALUES ('1', 'mbembridge0', 'cfairpool0@soundcloud.com'),
('2', 'shuller1', 'bgerrill1@mediafire.com'),
('3', 'nchretien2', 'llovat2@earthlink.net'),
('4', 'sskally3', 'asherrock3@sphinn.com'),
('5', 'aferne4', 'tvasyutin4@sakura.ne.jp'),
('6', 'rdaintree5', 'gsnugg5@mit.edu'),
('7', 'ssnel6', 'dbodicum6@godaddy.com'),
('8', 'hspeedin7', 'nhatwells7@psu.edu'),
('9', 'mheadford8', 'cpollendine8@pinterest.com'),
('10', 'oloveard9', 'cyule9@shareasale.com'),
('11', 'ldemarea', 'dmacnallya@cdc.gov'),
('12', 'kponsfordb', 'wpatersonb@uiuc.edu'),
('13', 'dbaughanc', 'atrucec@scribd.com'),
('14', 'ndubberd', 'iduigenand@washingtonpost.com'),
('15', 'cstoyelle', 'aengalle@desdev.cn'),
('16', 'dhattersleyf', 'darkinf@usda.gov'),
('17', 'atheakerg', 'fmauving@ibm.com'),
('18', 'mbussensh', 'stallh@usgs.gov'),
('19', 'krafteryi', 'eantonyi@ft.com'),
('20', 'msawnwyj', 'mbythewayj@foxnews.com'),
('21', 'smcisaack', 'tneilandsk@mediafire.com'),
('22', 'lmorll', 'rringhaml@sciencedirect.com'),
('23', 'phorsfieldm', 'eclaxtonm@live.com'),
('24', 'lthiesen', 'mkempen@g.co'),
('25', 'tsevitto', 'ctrowsdallo@angelfire.com'),
('26', 'ysmallpeacep', 'vfawdryp@buzzfeed.com'),
('27', 'ebeneixq', 'twrackq@istockphoto.com'),
('28', 'awilkesr', 'gyacobr@netscape.com'),
('29', 'jcacacies', 'gschurckes@soundcloud.com'),
('30', 'mgudgeont', 'cskelliont@ox.ac.uk'),
('31', 'bklimochkinu', 'cdallonu@fema.gov'),
('32', 'nexpositov', 'kfrancv@4shared.com'),
('33', 'mdraperw', 'ajohnstonw@ucsd.edu'),
('34', 'efoskenx', 'dmellsopx@nsw.gov.au'),
('35', 'omcgloney', 'fbenezeity@soundcloud.com'),
('36', 'rpepyez', 'erootsz@ebay.co.uk'),
('37', 'cstilly10', 'dfilov10@google.it'),
('38', 'jriche11', 'agerrett11@reddit.com'),
('39', 'asully12', 'imerrilees12@oakley.com'),
('40', 'hscarlon13', 'bshoard13@google.de'),
('41', 'jduddin14', 'fmongin14@github.com'),
('42', 'scloss15', 'ajaggar15@youtu.be'),
('43', 'dralestone16', 'jnudde16@pagesperso-orange.fr'),
('44', 'bduguid17', 'jcannop17@boston.com'),
('45', 'rgabotti18', 'ktrafford18@umn.edu'),
('46', 'asex19', 'pmaccoll19@google.cn'),
('47', 'mmackneis1a', 'bcastellani1a@dell.com'),
('48', 'moram1b', 'sheadech1b@multiply.com'),
('49', 'fcrier1c', 'hbarford1c@desdev.cn'),
('50', 'hsquelch1d', 'tgirtin1d@reuters.com'),
('51', 'aassante1e', 'nennals1e@cmu.edu'),
('52', 'rdonaher1f', 'rclementson1f@fema.gov'),
('53', 'ehellard1g', 'rbibey1g@imgur.com'),
('54', 'aportt1h', 'bvolker1h@google.pl'),
('55', 'mbrinsden1i', 'dbeedom1i@moonfruit.com'),
('56', 'ibunstone1j', 'bstoacley1j@nasa.gov'),
('57', 'kfaichnie1k', 'sdenizet1k@gravatar.com'),
('58', 'lmorshead1l', 'bmacrannell1l@prnewswire.com'),
('59', 'pjosipovic1m', 'mogles1m@mediafire.com'),
('60', 'cpebworth1n', 'dwoller1n@webmd.com'),
('61', 'dfiske1o', 'rmansford1o@amazon.com'),
('62', 'mwestfalen1p', 'fstronghill1p@usnews.com'),
('63', 'kdobbison1q', 'hfochs1q@rambler.ru'),
('64', 'bodowling1r', 'afenty1r@miibeian.gov.cn'),
('65', 'lcoombes1s', 'kbrisson1s@va.gov'),
('66', 'bdrewett1t', 'cmacanelley1t@stanford.edu'),
('67', 'ggerrens1u', 'msavile1u@ebay.com'),
('68', 'echatell1v', 'ggrindell1v@nba.com'),
('69', 'bhudel1w', 'atohill1w@noaa.gov'),
('70', 'kpersich1x', 'cwillder1x@nydailynews.com'),
('71', 'jbucklee1y', 'kpinck1y@oracle.com'),
('72', 'teverleigh1z', 'eclubb1z@pbs.org'),
('73', 'lgledstane20', 'smeert20@oracle.com'),
('74', 'sclorley21', 'lmouton21@forbes.com'),
('75', 'cbesnard22', 'rashlee22@slate.com'),
('76', 'nquiney23', 'ashinfield23@example.com'),
('77', 'gfeatenby24', 'mtuffey24@edublogs.org'),
('78', 'ahabard25', 'mhumberstone25@mozilla.com'),
('79', 'sroughsedge26', 'nfranciskiewicz26@addthis.com'),
('80', 'njobson27', 'nrupke27@ameblo.jp'),
('81', 'imarzellano28', 'hhacket28@auda.org.au'),
('82', 'gottee29', 'wwiggett29@economist.com'),
('83', 'fweddeburn2a', 'whupe2a@vistaprint.com'),
('84', 'afoulkes2b', 'tohdirscoll2b@studiopress.com'),
('85', 'dtreppas2c', 'eriggulsford2c@de.vu'),
('86', 'ntubbles2d', 'agravenor2d@admin.ch'),
('87', 'blough2e', 'gperes2e@samsung.com'),
('88', 'fschober2f', 'alawes2f@geocities.com'),
('89', 'fglawsop2g', 'eeykelhof2g@ehow.com'),
('90', 'cdunseath2h', 'bcollop2h@exblog.jp'),
('91', 'gshegog2i', 'cmaudett2i@biglobe.ne.jp'),
('92', 'rgerrets2j', 'lgantzer2j@instagram.com'),
('93', 'cwalkley2k', 'kthornhill2k@discuz.net'),
('94', 'cmeneghi2l', 'adailey2l@senate.gov'),
('95', 'estoade2m', 'rforre2m@intel.com'),
('96', 'drosenberg2n', 'cspaughton2n@free.fr'),
('97', 'crattry2o', 'ybernth2o@google.co.uk'),
('98', 'rmucklestone2p', 'ijannaway2p@discuz.net'),
('99', 'esoutherns2q', 'lfladgate2q@forbes.com'),
('100', 'jmcallaster2r', 'hcorking2r@bandcamp.com');
